gpu: "0"
multi_gpu: null

model_name: PointConv

full: False

evaluate: True
resume: True
ckpt_dir: ./pretrain_weights/PointConv/
arch: Separable
last_relu: False
allow_less_points: False

# general args
batch_size: 1
pretrain: S_851_0.0799.pth
dim: 3
num_points: 8192

DEVICE: cuda

dataset: KITTI # FlyingThings3DSubset KITTI
data_root: datasets

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# miscalleneous
workers: 0








